// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVWONfkFxNn8T2duiOyA0J3Jj2HtFanjQ',
    appId: '1:538649260345:android:c6bdf802f36aa3726c78e8',
    messagingSenderId: '538649260345',
    projectId: 'tiptipshine',
    storageBucket: 'tiptipshine.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC25brPR-MUOlsm3UzUZm_iQAv9nGygoiM',
    appId: '1:538649260345:ios:3813f1555acf512d6c78e8',
    messagingSenderId: '538649260345',
    projectId: 'tiptipshine',
    storageBucket: 'tiptipshine.appspot.com',
    androidClientId: '538649260345-15u1nmok4h1srfi7ffmcndrh4tqlc9id.apps.googleusercontent.com',
    iosClientId: '538649260345-jpncchn07ns798rhegj0ps12i138np57.apps.googleusercontent.com',
    iosBundleId: 'com.example.karachiEducation',
  );
}
